name: Order Service CI/CD Pipeline

on:
  push:
    branches:
      - master # Runs pipeline when pushing to master

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest # Runs on GitHub-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t jashpatel1511/web-order-service:latest .
          docker push jashpatel1511/web-order-service:latest

  deploy:
    name: Deploy to EKS Cluster
    needs: build-and-push
    runs-on: ubuntu-latest # Runs on GitHub-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{secrets.AWS_CLUSTER_NAME}}

      - name: Apply Kubernetes Resources
        run: |
          kubectl apply -f k8s/OrderService-configMap.yaml
          kubectl apply -f k8s/OrderService-secret.yaml
          kubectl apply -f k8s/OrderService-deployment.yaml
