name: Order Service CI/CD Pipeline

on:
  push:
    branches:
      - master # Runs pipeline when pushing to master

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: self-hosted # Runs on GitHub-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t jashpatel1511/web-order-service:latest .
          docker push jashpatel1511/web-order-service:latest

  deploy:
    name: Deploy to kind Kubernetes Cluster
    needs: build-and-push # Runs only if build-and-push is successful
    runs-on: self-hosted # Runs on your self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Kubeconfig for kind Cluster
        run: |
          # Set up kubeconfig to point to the running kind cluster
          kind get kubeconfig --name k8s-cluster > $HOME/.kube/config

      - name: Load Docker Image into kind
        run: |
          kind load docker-image jashpatel1511/web-order-service:latest

      - name: Apply Kubernetes Deployment
        run: |
          cd /home/${{ secrets.VM_USER }}/actions-runner/_work/${{ github.repository }}/k8s
          kubectl apply -f .

      - name: Cleanup
        run: |
          echo "No need to delete kind cluster as it is already up and running."
